DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ledgerly_app') THEN
    CREATE ROLE ledgerly_app LOGIN PASSWORD 'ledgerly_app';
  END IF;
END $$;

GRANT CONNECT ON DATABASE ledgerly TO ledgerly_app;
GRANT USAGE ON SCHEMA public TO ledgerly_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ledgerly_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ledgerly_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ledgerly_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ledgerly_app;
